/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreationPlayRouteImport } from './routes/creation/play'
import { Route as CreationNewRouteImport } from './routes/creation/new'
import { Route as CreationIdPreviewRouteImport } from './routes/creation/$id.preview'
import { Route as CreationIdEditRouteImport } from './routes/creation/$id.edit'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationPlayRoute = CreationPlayRouteImport.update({
  id: '/creation/play',
  path: '/creation/play',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationNewRoute = CreationNewRouteImport.update({
  id: '/creation/new',
  path: '/creation/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationIdPreviewRoute = CreationIdPreviewRouteImport.update({
  id: '/creation/$id/preview',
  path: '/creation/$id/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationIdEditRoute = CreationIdEditRouteImport.update({
  id: '/creation/$id/edit',
  path: '/creation/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/creation/new': typeof CreationNewRoute
  '/creation/play': typeof CreationPlayRoute
  '/creation/$id/edit': typeof CreationIdEditRoute
  '/creation/$id/preview': typeof CreationIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/creation/new': typeof CreationNewRoute
  '/creation/play': typeof CreationPlayRoute
  '/creation/$id/edit': typeof CreationIdEditRoute
  '/creation/$id/preview': typeof CreationIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/creation/new': typeof CreationNewRoute
  '/creation/play': typeof CreationPlayRoute
  '/creation/$id/edit': typeof CreationIdEditRoute
  '/creation/$id/preview': typeof CreationIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/creator'
    | '/explore'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/creation/new'
    | '/creation/play'
    | '/creation/$id/edit'
    | '/creation/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/creator'
    | '/explore'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/creation/new'
    | '/creation/play'
    | '/creation/$id/edit'
    | '/creation/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/creator'
    | '/explore'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/creation/new'
    | '/creation/play'
    | '/creation/$id/edit'
    | '/creation/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CreatorRoute: typeof CreatorRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  CreationNewRoute: typeof CreationNewRoute
  CreationPlayRoute: typeof CreationPlayRoute
  CreationIdEditRoute: typeof CreationIdEditRoute
  CreationIdPreviewRoute: typeof CreationIdPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation/play': {
      id: '/creation/play'
      path: '/creation/play'
      fullPath: '/creation/play'
      preLoaderRoute: typeof CreationPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation/new': {
      id: '/creation/new'
      path: '/creation/new'
      fullPath: '/creation/new'
      preLoaderRoute: typeof CreationNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation/$id/preview': {
      id: '/creation/$id/preview'
      path: '/creation/$id/preview'
      fullPath: '/creation/$id/preview'
      preLoaderRoute: typeof CreationIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation/$id/edit': {
      id: '/creation/$id/edit'
      path: '/creation/$id/edit'
      fullPath: '/creation/$id/edit'
      preLoaderRoute: typeof CreationIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CreatorRoute: CreatorRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  CreationNewRoute: CreationNewRoute,
  CreationPlayRoute: CreationPlayRoute,
  CreationIdEditRoute: CreationIdEditRoute,
  CreationIdPreviewRoute: CreationIdPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
