/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestPreviewRouteImport } from './routes/quest/preview'
import { Route as QuestPlayRouteImport } from './routes/quest/play'

const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestPreviewRoute = QuestPreviewRouteImport.update({
  id: '/quest/preview',
  path: '/quest/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestPlayRoute = QuestPlayRouteImport.update({
  id: '/quest/play',
  path: '/quest/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/quest/play': typeof QuestPlayRoute
  '/quest/preview': typeof QuestPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/quest/play': typeof QuestPlayRoute
  '/quest/preview': typeof QuestPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/quest/play': typeof QuestPlayRoute
  '/quest/preview': typeof QuestPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/explore' | '/quest/play' | '/quest/preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explore' | '/quest/play' | '/quest/preview'
  id: '__root__' | '/' | '/explore' | '/quest/play' | '/quest/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  QuestPlayRoute: typeof QuestPlayRoute
  QuestPreviewRoute: typeof QuestPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quest/preview': {
      id: '/quest/preview'
      path: '/quest/preview'
      fullPath: '/quest/preview'
      preLoaderRoute: typeof QuestPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quest/play': {
      id: '/quest/play'
      path: '/quest/play'
      fullPath: '/quest/play'
      preLoaderRoute: typeof QuestPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  QuestPlayRoute: QuestPlayRoute,
  QuestPreviewRoute: QuestPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
