/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TextToLoudRouteImport } from './routes/text-to-loud'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExtractMediaRouteImport } from './routes/extract-media'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUsagesRouteImport } from './routes/admin/usages'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminActivitiesRouteImport } from './routes/admin/activities'
import { Route as ActivityResultsRouteImport } from './routes/activity/results'
import { Route as ActivityMeRouteImport } from './routes/activity/me'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as BlogCategorySlugRouteImport } from './routes/blog/category.$slug'
import { Route as ActivityPlayIdRouteImport } from './routes/activity/play.$id'
import { Route as AdminPostsUploadIdRouteImport } from './routes/admin/posts/upload.$id'
import { Route as ActivityUploadQuizIdRouteImport } from './routes/activity/upload/quiz.$id'
import { Route as ActivityUploadQuestIdRouteImport } from './routes/activity/upload/quest.$id'
import { Route as ActivityUploadLessonIdRouteImport } from './routes/activity/upload/lesson.$id'

const TextToLoudRoute = TextToLoudRouteImport.update({
  id: '/text-to-loud',
  path: '/text-to-loud',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractMediaRoute = ExtractMediaRouteImport.update({
  id: '/extract-media',
  path: '/extract-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsagesRoute = AdminUsagesRouteImport.update({
  id: '/admin/usages',
  path: '/admin/usages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/admin/activities',
  path: '/admin/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityResultsRoute = ActivityResultsRouteImport.update({
  id: '/activity/results',
  path: '/activity/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityMeRoute = ActivityMeRouteImport.update({
  id: '/activity/me',
  path: '/activity/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/admin/posts/',
  path: '/admin/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityPlayIdRoute = ActivityPlayIdRouteImport.update({
  id: '/activity/play/$id',
  path: '/activity/play/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsUploadIdRoute = AdminPostsUploadIdRouteImport.update({
  id: '/admin/posts/upload/$id',
  path: '/admin/posts/upload/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityUploadQuizIdRoute = ActivityUploadQuizIdRouteImport.update({
  id: '/activity/upload/quiz/$id',
  path: '/activity/upload/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityUploadQuestIdRoute = ActivityUploadQuestIdRouteImport.update({
  id: '/activity/upload/quest/$id',
  path: '/activity/upload/quest/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityUploadLessonIdRoute = ActivityUploadLessonIdRouteImport.update({
  id: '/activity/upload/lesson/$id',
  path: '/activity/upload/lesson/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/delete-account': typeof DeleteAccountRoute
  '/explore': typeof ExploreRoute
  '/extract-media': typeof ExtractMediaRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/terms': typeof TermsRoute
  '/text-to-loud': typeof TextToLoudRoute
  '/activity/me': typeof ActivityMeRoute
  '/activity/results': typeof ActivityResultsRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/usages': typeof AdminUsagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/activity/play/$id': typeof ActivityPlayIdRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/activity/upload/lesson/$id': typeof ActivityUploadLessonIdRoute
  '/activity/upload/quest/$id': typeof ActivityUploadQuestIdRoute
  '/activity/upload/quiz/$id': typeof ActivityUploadQuizIdRoute
  '/admin/posts/upload/$id': typeof AdminPostsUploadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/delete-account': typeof DeleteAccountRoute
  '/explore': typeof ExploreRoute
  '/extract-media': typeof ExtractMediaRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/terms': typeof TermsRoute
  '/text-to-loud': typeof TextToLoudRoute
  '/activity/me': typeof ActivityMeRoute
  '/activity/results': typeof ActivityResultsRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/usages': typeof AdminUsagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/activity/play/$id': typeof ActivityPlayIdRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/activity/upload/lesson/$id': typeof ActivityUploadLessonIdRoute
  '/activity/upload/quest/$id': typeof ActivityUploadQuestIdRoute
  '/activity/upload/quiz/$id': typeof ActivityUploadQuizIdRoute
  '/admin/posts/upload/$id': typeof AdminPostsUploadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/delete-account': typeof DeleteAccountRoute
  '/explore': typeof ExploreRoute
  '/extract-media': typeof ExtractMediaRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/terms': typeof TermsRoute
  '/text-to-loud': typeof TextToLoudRoute
  '/activity/me': typeof ActivityMeRoute
  '/activity/results': typeof ActivityResultsRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/usages': typeof AdminUsagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/activity/play/$id': typeof ActivityPlayIdRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/activity/upload/lesson/$id': typeof ActivityUploadLessonIdRoute
  '/activity/upload/quest/$id': typeof ActivityUploadQuestIdRoute
  '/activity/upload/quiz/$id': typeof ActivityUploadQuizIdRoute
  '/admin/posts/upload/$id': typeof AdminPostsUploadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/create'
    | '/delete-account'
    | '/explore'
    | '/extract-media'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/saved'
    | '/terms'
    | '/text-to-loud'
    | '/activity/me'
    | '/activity/results'
    | '/admin/activities'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/usages'
    | '/admin/users'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/admin'
    | '/blog'
    | '/categories'
    | '/activity/play/$id'
    | '/blog/category/$slug'
    | '/admin/posts'
    | '/activity/upload/lesson/$id'
    | '/activity/upload/quest/$id'
    | '/activity/upload/quiz/$id'
    | '/admin/posts/upload/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/create'
    | '/delete-account'
    | '/explore'
    | '/extract-media'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/saved'
    | '/terms'
    | '/text-to-loud'
    | '/activity/me'
    | '/activity/results'
    | '/admin/activities'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/usages'
    | '/admin/users'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/admin'
    | '/blog'
    | '/categories'
    | '/activity/play/$id'
    | '/blog/category/$slug'
    | '/admin/posts'
    | '/activity/upload/lesson/$id'
    | '/activity/upload/quest/$id'
    | '/activity/upload/quiz/$id'
    | '/admin/posts/upload/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/create'
    | '/delete-account'
    | '/explore'
    | '/extract-media'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/saved'
    | '/terms'
    | '/text-to-loud'
    | '/activity/me'
    | '/activity/results'
    | '/admin/activities'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/usages'
    | '/admin/users'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/admin/'
    | '/blog/'
    | '/categories/'
    | '/activity/play/$id'
    | '/blog/category/$slug'
    | '/admin/posts/'
    | '/activity/upload/lesson/$id'
    | '/activity/upload/quest/$id'
    | '/activity/upload/quiz/$id'
    | '/admin/posts/upload/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CreateRoute: typeof CreateRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  ExploreRoute: typeof ExploreRoute
  ExtractMediaRoute: typeof ExtractMediaRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  TermsRoute: typeof TermsRoute
  TextToLoudRoute: typeof TextToLoudRoute
  ActivityMeRoute: typeof ActivityMeRoute
  ActivityResultsRoute: typeof ActivityResultsRoute
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsagesRoute: typeof AdminUsagesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ActivityPlayIdRoute: typeof ActivityPlayIdRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  ActivityUploadLessonIdRoute: typeof ActivityUploadLessonIdRoute
  ActivityUploadQuestIdRoute: typeof ActivityUploadQuestIdRoute
  ActivityUploadQuizIdRoute: typeof ActivityUploadQuizIdRoute
  AdminPostsUploadIdRoute: typeof AdminPostsUploadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/text-to-loud': {
      id: '/text-to-loud'
      path: '/text-to-loud'
      fullPath: '/text-to-loud'
      preLoaderRoute: typeof TextToLoudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract-media': {
      id: '/extract-media'
      path: '/extract-media'
      fullPath: '/extract-media'
      preLoaderRoute: typeof ExtractMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usages': {
      id: '/admin/usages'
      path: '/admin/usages'
      fullPath: '/admin/usages'
      preLoaderRoute: typeof AdminUsagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/admin/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/results': {
      id: '/activity/results'
      path: '/activity/results'
      fullPath: '/activity/results'
      preLoaderRoute: typeof ActivityResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/me': {
      id: '/activity/me'
      path: '/activity/me'
      fullPath: '/activity/me'
      preLoaderRoute: typeof ActivityMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/admin/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/play/$id': {
      id: '/activity/play/$id'
      path: '/activity/play/$id'
      fullPath: '/activity/play/$id'
      preLoaderRoute: typeof ActivityPlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/upload/$id': {
      id: '/admin/posts/upload/$id'
      path: '/admin/posts/upload/$id'
      fullPath: '/admin/posts/upload/$id'
      preLoaderRoute: typeof AdminPostsUploadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/upload/quiz/$id': {
      id: '/activity/upload/quiz/$id'
      path: '/activity/upload/quiz/$id'
      fullPath: '/activity/upload/quiz/$id'
      preLoaderRoute: typeof ActivityUploadQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/upload/quest/$id': {
      id: '/activity/upload/quest/$id'
      path: '/activity/upload/quest/$id'
      fullPath: '/activity/upload/quest/$id'
      preLoaderRoute: typeof ActivityUploadQuestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/upload/lesson/$id': {
      id: '/activity/upload/lesson/$id'
      path: '/activity/upload/lesson/$id'
      fullPath: '/activity/upload/lesson/$id'
      preLoaderRoute: typeof ActivityUploadLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CreateRoute: CreateRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  ExploreRoute: ExploreRoute,
  ExtractMediaRoute: ExtractMediaRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  TermsRoute: TermsRoute,
  TextToLoudRoute: TextToLoudRoute,
  ActivityMeRoute: ActivityMeRoute,
  ActivityResultsRoute: ActivityResultsRoute,
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsagesRoute: AdminUsagesRoute,
  AdminUsersRoute: AdminUsersRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ActivityPlayIdRoute: ActivityPlayIdRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  ActivityUploadLessonIdRoute: ActivityUploadLessonIdRoute,
  ActivityUploadQuestIdRoute: ActivityUploadQuestIdRoute,
  ActivityUploadQuizIdRoute: ActivityUploadQuizIdRoute,
  AdminPostsUploadIdRoute: AdminPostsUploadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
